services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        APP_VERSION: ${VERSION} # bakes into image, used by entrypoint/env.js
    environment:
      NODE_ENV: production
      APP_VERSION: ${VERSION} # ← runtime env, used by /api/version
    volumes:
      - ./uploads:/input
      - ./data:/data
      - ./extension:/extension:ro
    tmpfs:
      - /work
    ports:
      - "3004:3004"

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        APP_VERSION: ${VERSION} # ← bakes into image, used by entrypoint/env.js
    ports:
      - "3003:3003"
    volumes:
      - ./data:/usr/share/nginx/html/data:ro
      - ./extension:/usr/share/nginx/html/extension:ro
    depends_on:
      - api
    environment:
      APP_VERSION: ${VERSION}
