services:
  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      BACKUP_ZIP: /input/PlayniteBackup.zip
    volumes:
      - ./backups:/input:ro
      - ./data:/data
    command: ["/input/PlayniteBackup.zip", "/data"]

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./data:/usr/share/nginx/html/data:ro 
    depends_on:
      - worker

volumes:
  data:
