services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - ./uploads:/input                  # where you drop/import stuff
      - ./data:/data                      # where API writes exports/media
      - ./extension:/extension:ro         # API serves /api/extension/download from here
    tmpfs:
      - /work
    ports:
      - "3004:3004"

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./data:/usr/share/nginx/html/data:ro            # static /data/** directly
      - ./extension:/usr/share/nginx/html/extension:ro  # static /extension/latest.pext
    depends_on:
      - api
