services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - ./backups:/input
      - ./data:/data 
    tmpfs:
      - /work
    ports:
      - "3000:3000"

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "3001:80"
    volumes:
      - ./data:/usr/share/nginx/html/data:ro 
    depends_on:
      - api

volumes:
  data:
